# Generated by Django 5.2.1 on 2025-09-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(db_column='product_id', max_length=50, unique=True),
        ),
    ]
